### ISSUE TITLE
Validation Array

### ISSUE THREAD

**Issue by Jeniphan** [nestjs/class-validator#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi, I am try use validation in NestJS follow document, I need send this query "/api/tournaments/TournamentsList?filterBy=id&filter=1&searchBy=title&search=akiira" is normally query and this my function in controller

`@Get('TournamentsList')
  @ApiCreatedResponse({ type: MessageResultAPIModel })
  @UsePipes(new ValidationPipe())
  async TournamentsList(
    @Query() dataQuery: QueryObject
  ) {
    try {
     console.log(dataQuery.filterBy)
      return this.tournamentService.TournamentListService(dataQuery)

    } catch (err) {

    }
  }`

and this my class QueryObject

`export class QueryObject {
  @IsString({ each: true })
  @IsArray()
  @IsOptional()
  filterBy?: string[]

  @IsString({ each: true }) 
  @IsArray()
  @IsOptional()
  filter?: string[]

  @IsString({ each: true }) 
  @IsArray()
  @IsOptional()
  searchBy?: string[]

  @IsString()
  @IsOptional()
  search?: string

  @IsString()
  @IsOptional()
  sortBy?: string

  @IsEnum(ESorter)
  @IsOptional()
  sort: Sorter

  @IsNumber()
  @IsOptional()
  page: number

  @IsNumber()
  @IsOptional()
  perPage: number

  @IsString({ each: true }) 
  @IsArray()
  @IsOptional()
  selectField?: string[]

  @IsBoolean()
  @IsOptional()
  TransformDateTime: boolean
}`

When I send request to server have error 
`{
    "statusCode": 400,
    "message": [
        "filterBy must be an array",
        "filter must be an array",
        "searchBy must be an array"
    ],
    "error": "Bad Request"
}`

And If I remove `@IsArray()` result log is `"id"` should `["id"]`.

How I can validation is code. Thanks support.

### Minimum reproduction code

https://github.com/Jeniphan

### Expected behavior

And If I remove `@IsArray()` result log is `"id"` should `["id"]`.

### Package version

^0.14.0

### Node.js version

^9.0.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
