### ISSUE TITLE
ESM error with dependency `libphonenumber-js`

### ISSUE THREAD

**Issue by MichaelSp** [nestjs/class-validator#386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
../node_modules/.pnpm/@nestjs+class-validator@0.13.4/node_modules/@nestjs/class-validator/types/decorator/string/IsPhoneNumber.d.ts:2:29 - error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("libphonenumber-js")' call instead.

2 import { CountryCode } from 'libphonenumber-js';
                               ~~~~~~~~~~~~~~~~~~~

../node_modules/.pnpm/libphonenumber-js@1.10.15/node_modules/libphonenumber-js/index.d.ts:18:8 - error TS2834: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Consider adding an extension to the import path.

18 } from './types';
          ~~~~~~~~~

```

### Minimum reproduction code

no

### Expected behavior

no error message

### Package version

0.13.4

### NestJS version

9.3.9

### Node.js version

20.1.8

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

upstream also suffers from that: https://github.com/typestack/class-validator/issues/1947#issuecomment-1767119708

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/typestack/class-validator/issues/1947
