### ISSUE TITLE
Validate dynamic key in the DTO

### ISSUE THREAD

**Issue by AmitGit217** [nestjs/class-validator#393]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In some use cases, it is necessary to validate dynamic keys within a DTO. For example, when keys are not predefined but are generated dynamically based on certain conditions. Currently, class-validator does not provide a straightforward way to validate these dynamic keys.

Consider the following example:

```
class ClassName {
  @IsNumber()
  [key: string]: number;
}
```

This type of validation is not supported, leading to difficulties in scenarios where keys are generated at runtime, and their validation is crucial.

### Describe the solution you'd like

I would like to see support for validating dynamic keys within DTOs. Specifically, a decorator or mechanism that allows the validation of keys that are not predefined in the class but are still subject to validation rules like @IsNumber, @IsString, etc.

A possible solution could involve extending the class-validator decorators to handle dynamic key validation or introducing a new decorator designed for this purpose.

Something maybe like @KeyIsString ?

### What is the motivation / use case for changing the behavior?

The motivation is to enable developers to validate DTOs with dynamic keys easily. This is particularly useful in applications where the structure of data is not entirely static, and certain keys are generated based on runtime conditions or user input.

This change would enhance the flexibility and robustness of data validation within NestJS applications using class-validator.

**Comment by kamilmysliwiec** [comment]
This is impossible due to how TypeScript works (no "[key: string]: number" metadata left in the build artifact)
