### ISSUE TITLE
fix: medium vulnerability reported by snyk

### ISSUE THREAD

**Issue by ayeletdasa** [nestjs/class-validator#59]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Snyk security scan reports that nestjs/class-validator has medium vulnerability related to dependency out-of-date.
The medium vulnerability related to dependency out-of-date can be fixed easily by upgrading the validation dependency to 13.7.0 version.

### Minimum reproduction code

https://snyk.io/vuln/npm%3Avalidator

### Expected behavior

Library should not have security vulnerabilities.

### Package version

0.13.3

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Renovate & dependabot will take care of updating deps automatically.
